//USER REGISTRATION
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
//USER LOGIN
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
//USER PROFILE
export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';
//USER UPDATE
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
// FETCH USERS
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'CREATE_USERS_FAIL';

/*----------------------------------------------------------------*/
//CREATE STUDENT DATA
export const CREATE_STUDENTDATA_REQUEST = 'CREATE_STUDENT_REQUEST';
export const CREATE_STUDENTDATA_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const CREATE_STUDENTDATA_FAIL = 'CREATE_STUDENT_FAIL';
// FETCH STUDENT DATA
export const FETCH_STUDENTDATA_REQUEST = 'FETCH_STUDENTDATA_REQUEST';
export const FETCH_STUDENTDATA_SUCCESS = 'FETCH_STUDENTDATA_SUCCESS';
export const FETCH_STUDENTDATA_FAIL = 'FETCH_STUDENTDATA_FAIL';
//DELETE STUDENT DATA
export const DELETE_STUDENTDATA_REQUEST = 'DELETE_STUDENTDATA_REQUEST';
export const DELETE_STUDENTDATA_SUCCESS = 'DELETE_STUDENTDATA_SUCCESS';
export const DELETE_STUDENTDATA_FAIL = 'DELETE_STUDENTDATA_FAIL';
//STUDENT PROFILE DETAIL
export const STUDENTPROFILE_DETAIL_REQUEST = 'STUDENTPROFILE_DETAIL_REQUEST';
export const STUDENTPROFILE_DETAIL_SUCCESS = 'STUDENTPROFILE_DETAIL_SUCCESS';
export const STUDENTPROFILE_DETAIL_FAIL = 'STUDENTPROFILE_DETAIL_FAIL';
//UPDATE PROFILE DETAIL
export const PROFILEDETAIL_UPDATE_REQUEST = 'PROFILEDETAIL_UPDATE_REQUEST';
export const PROFILEDETAIL_UPDATE_SUCCESS = 'PROFILEDETAIL_UPDATE_SUCCESS';
export const PROFILEDETAIL_UPDATE_FAIL = 'PROFILEDETAIL_UPDATE_FAIL';
/*----------------------------------------------------------------*/

/*----------------------------------------------------------------*/
//CREATE PROFESSOR DATA
export const CREATE_PROFESSORDATA_REQUEST = 'CREATE_PROFESSOR_REQUEST';
export const CREATE_PROFESSORDATA_SUCCESS = 'CREATE_PROFESSOR_SUCCESS';
export const CREATE_PROFESSORDATA_FAIL = 'CREATE_PROFESSOR_FAIL';
// FETCH PROFESSOR DATA
export const FETCH_PROFESSORDATA_REQUEST = 'FETCH_PROFESSORDATA_REQUEST';
export const FETCH_PROFESSORDATA_SUCCESS = 'FETCH_PROFESSORDATA_SUCCESS';
export const FETCH_PROFESSORDATA_FAIL = 'FETCH_PROFESSORDATA_FAIL';
//DELETE PROFESSOR DATA
export const DELETE_STUDENTDATA_REQUEST = 'DELETE_PROFESSORDATA_REQUEST';
export const DELETE_STUDENTDATA_SUCCESS = 'DELETE_PROFESSORDATA_SUCCESS';
export const DELETE_STUDENTDATA_FAIL = 'DELETE_PROFESSORDATA_FAIL';
//PROFESSOR PROFILE DETAIL
export const PROFESSORPROFILE_DETAIL_REQUEST = 'PROFESSORPROFILE_DETAIL_REQUEST';
export const PROFESSORPROFILE_DETAIL_SUCCESS = 'PROFESSORPROFILE_DETAIL_SUCCESS';
export const PROFESSORPROFILE_DETAIL_FAIL = 'PROFESSORPROFILE_DETAIL_FAIL';
//UPDATE PROFILE DETAIL
export const PROFILEDETAIL_UPDATE_REQUEST = 'PROFILEDETAIL_UPDATE_REQUEST';
export const PROFILEDETAIL_UPDATE_SUCCESS = 'PROFILEDETAIL_UPDATE_SUCCESS';
export const PROFILEDETAIL_UPDATE_FAIL = 'PROFILEDETAIL_UPDATE_FAIL';
/*----------------------------------------------------------------*/
